### ISSUE TITLE
`install.py` fails on Windows

### ISSUE THREAD

**Issue by jordanbtucker** [Fannovel16/comfy_controlnet_preprocessors#2] opened 2023-03-15 16:15 UTC
When trying to run `python install.py` on Windows 10, I get the following error.

```
Installing requirements...
Collecting opencv-contrib-python
  Using cached opencv_contrib_python-4.7.0.72-cp37-abi3-win_amd64.whl (44.9 MB)
Collecting opencv-python
  Using cached opencv_python-4.7.0.72-cp37-abi3-win_amd64.whl (38.2 MB)
Collecting numpy==1.23.1
  Using cached numpy-1.23.1.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting timm==0.6.12
  Using cached timm-0.6.12-py3-none-any.whl (549 kB)
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement torchvision (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3)
ERROR: No matching distribution found for torchvision
```

This is using the embedded python that comes with ComfyUI, which is 3.10.9.

**Comment by jordanbtucker** [comment] 2023-03-16 00:04
I got it to work by following these alternate install instructions.

```
cd ComfyUI/custom_nodes
git clone https://github.com/Fannovel16/comfy_controlnet_preprocessors
cd comfy_controlnet_preprocessors
..\..\..\python_embeded\python.exe -m pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117
```

**Comment by drorlazar** [comment] 2023-03-16 09:14
I'm getting this error:

 ```
Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\DrorLazar\AppData\Local\Temp\pip-install-vbopr2bu\future_6b00de7e93d640adabeddf3b6ad931b8\setup.py", line 86, in <module>
          import src.future
      ModuleNotFoundError: No module named 'src'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
any ideas?

**Comment by jordanbtucker** [comment] 2023-03-16 16:04
@drorlazar Is that when you're trying to install comfy_controlnet_preprocessors or when you're trying to run ComfyUI?

**Comment by fretts88** [comment] 2023-03-16 18:17
> @drorlazar Is that when you're trying to install comfy_controlnet_preprocessors or when you're trying to run ComfyUI?

I get the same, its when running the install

..\..\..\python_embeded\python.exe -m pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117 --no-warn-script-location

**Comment by nistvan86** [comment] 2023-03-17 23:38
I'm getting the same error during install.

**Comment by paulo-coronado** [comment] 2023-03-18 02:06
I am also facing the same error when running:
```
..\..\..\python_embeded\python.exe -m pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117 --no-warn-script-location
```

**Comment by Fannovel16** [comment] 2023-03-18 07:44
> I might be wrong but I don't think this is a mandatory package.

It is used to download models.

I will try my best to fix it. Package managing is truely a pain in ass.

**Comment by paulo-coronado** [comment] 2023-03-18 11:04
@Fannovel16 Yeahh, it is!! I really want to fix the tool, it will be a game changer! If you need any help, count on me! Here is my Discord profile: **@pcoronado#4338**

**Comment by Fannovel16** [comment] 2023-03-18 11:35
@paulo-coronado Fixed in this PR: https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/b4e4493bee1d738e0862a99ce3cba88e29a0c9c0

The problem is that the original ControlNet repo use basicsr to just download checkpoint files. To do so, it will install future package. For some unknown reasons, the python build from the standalone version can't install it. So I simply removed that package and put load_file_from_url's code into util.py

**Closed by Fannovel16** 2023-03-18 11:35 UTC
